config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :tvs



  #   require "sidekiq/web"
  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :tv
end

app/models/tv.rb
class Tv < ApplicationRecord
  has_many :transactions
  has_many_attached :photos

  include PgSearch::Model
  pg_search_scope :search_by_name_and_year,
  against: [ :name, :year ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
has_many :transactions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    if params[:query].present?
      @tvs = Tv.search_by_name_and_year(params[:query])
    else
      @tvs = Tv.all
    end
    @best_sellers = Tv.order(:price).limit(1)
    @reviews = [{ name: "Mo", content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum deserunt sequi sed sunt nihil quam eos voluptas fugiat nulla voluptate eligendi magni, expedita, dicta ut quisquam. Voluptatem, eaque voluptate alias!
" }, { name: "Mo", content: "We offer a Great Service"}, { name: "Mo", content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum deserunt sequi sed sunt nihil quam eos voluptas fugiat nulla voluptate eligendi magni, expedita, dicta ut quisquam. Voluptatem, eaque voluptate alias!
"}]

  end

end

app/controllers/transaction_controller.rb
class TransactionController < ApplicationController
end

app/controllers/tvs_controller.rb
class TvsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @tvs_all = Tv.all
    @tvs = Tv.all
    if !params[:query].nil?
      @tvs = Tv.where('name ILIKE ?', params[:query])
    end
    if !params[:search].nil?
      params[:search].each do |key, value|
        @tvs = @tvs.where(key => value) if value.present?
      end
    end
    # @recent_tvs = Tv.where(@tv.id = current)
  end

  def show
    @tv = Tv.find(params[:id])
    # @similar_tvs = Tv.where(["name = ? and id != ?", @tv.name, @tv.id]).limit(3)

    @similar_tvs = Tv.where(["name = ? and id != ?", @tv.name, @tv.id]).limit(3)
  end

  def new
   @tv_new = Tv.new
  end

  def create
    @tv_new = Tv.new(tv_params)
    if @tv_new.save
      flash[:success] = "Your Tv Has been listed"
      redirect_to tvs_path
    else
      render :new
    end
  end

  def edit
    @tv = Tv.find(params[:id])
  end

  def update
    @tv = Tv.find(params[:id])
    @tv.update(tv_params)
    redirect_to tvs_path(current_user)
    @tv.save
  end

  def destroy
    @tv = Tv.find(params[:id])
    @tv.destroy(tv_params)
    redirect_to user_path(current_user)
  end

  def tv_params
    params.require(:tv).permit(:price, :model, :size, :year, :brand, :specification, :description, photos: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discounttvs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>


  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>


    <%= yield %>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<html>
<body>.

  <div class="banner mb-3">
    <div class="slogan-box text-center">
      <h1 class=" mb-4">ORDER TODAY. . .  <strong>PAY ON DELIVERY DAY</strong></h1>
      <button type="button" class="dtv-button"><%= link_to "Shop Now", tvs_path, class: "dtv-button" %></button>
    </div>
    <div class="mt-5">
     <!--  <h2 class="text-center mt-3">Search for your new TV here</h2> -->
      <%= render 'shared/search' %>
    </div>
  </div>
<!--   <div class="row justify-content-center mt-3"></div> -->
  <div class="container mb-4">
    <div class="" data-aos="zoom-in">
      <h2 class="grid-title-font text-center border-bottom mb-3 pb-3 mt-5 ">TV Range</h2>
      <div class="row wrap">
        <div class="col-lg-6 col-md-12 col-sm-12 box-long-padding">
        <%= link_to tvs_path do %>
          <div class="grid-box-long">
            <img class="grid-box-image-long" src="https://discounttvs.co.uk/wp-content/uploads/2020/02/4K-TV.jpg" alt="">
            <div class="text-inner-box">
            <h2>4K TV</h2>
            </div>
          </div>
        </div>
        <% end %>
        <div class="col-lg-6 col-md-12 col-sm-12 box-tr-padding">
        <%= link_to tvs_path do %>
          <div class="box-top-right">
            <img class="box-top-right-image" src="https://discounttvs.co.uk/wp-content/uploads/2020/02/Curved-TV.png" alt="">
          <div class="text-inner">
            <h2>Curved TV</h2>
          </div>
          </div>
        </div>
        <% end %>
      </div>
      <div class="row">
        <div class="col-lg-3 col-md-12 col-sm-12">
          <%= link_to tvs_path do %>
          <div class="grid-bottom">
            <img class="grid-bottom-image" src="https://discounttvs.co.uk/wp-content/uploads/2020/02/8K-TV.jpg" alt="">
            <div class="text-inner">
              <h2>8K TV</h2>
            </div>
          </div>
          <% end %>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
          <%= link_to tvs_path do %>
          <div class="grid-bottom">
            <img class="grid-bottom-image" src="https://discounttvs.co.uk/wp-content/uploads/2020/02/TheFrameTV.jpg" alt="">
            <div class="text-inner-box3">
              <h2>The Frame TV</h2>
            </div>
          </div>
          <% end %>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
          <%= link_to tvs_path do %>
          <div class="grid-bottom">
            <img class="grid-bottom-image" src="https://discounttvs.co.uk/wp-content/uploads/2020/02/OLED-TV.jpg" alt="">
            <div class="text-inner">
              <h2>OLED TV</h2>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="parallax">
    <div id="style="height:100px;background-color:transparent;font-size:18px></div>
  </div>
    <!-- <div class="text-big" data-aos="fade-right">
      <h2>We are a group of analytically minded individuals, who seek to provide a new perspective on how organisational value can be distributed.</h2>
    </div> -->

  <div class="order-process-container">
    <div class="container">
      <%= render 'shared/cardhome' %>
    </div>
  </div>

  <div class="container">
    <h2 class="bestsellers-title text-center border-bottom m-5 p-3">Best Sellers</h2>
    <div class="row d-flex justify-content-around mt-2 pb-5">
      <% @best_sellers.each do |tv| %>
        <%= render 'shared/bestsellers' %>
      <% end %>
    </div>
  </div>

  <div class="parallax">
    <div id="style="height:100px;background-color:transparent;font-size:18px></div>
  </div>

  <div class="review-container">
    <h4 class="text-center mt-2 mb-2">What our customers think</h4>
    <div id="carouselExampleIndicators" class="carousel-slide bg-transparent m-3" data-ride="carousel">
      <div class="carousel-inner">
      <!-- for every review, we are going to iterate over and if its the first review, then give it the active class otherwise its not active. (needs to be active, because additional JS is being run in the background for each carosel) -->
        <% @reviews.each_with_index do |review, index| %>
          <div class="carousel-item discounttv-carosel-slide text-center  <%= index == 0 ? 'active' : '' %>">
            <h2>"<%= review[:content] %>"</h2>
            <h3><%= review[:name] %></h3>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="">
    <%= render 'shared/form' %>
  </div>

  <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>

  <%= yield %>

</body>
</html>

app/views/shared/_bestsellers.html.erb
<div class="best_sellers--styles">
  <% @best_sellers.each do |tv| %>
  <%= link_to tv_path(tv) do %>
  <div class="product-card" style="width: 18rem;">
    <div class="product-image border-bottom bg-grey pb-2">
      <img class="card-img"  src="https://discounttvs.co.uk/wp-content/uploads/2020/02/4K-TV.jpg" alt="Card image cap">
    </div>
    <!-- <div class="product-image" style="background-image: url(<%#= tv.photos.first ? (cl_image_path tv.photos.first.key, crop: :fill) : ""  %>)"></div> -->
    <div class="tv-index-product-description pt-1">
      <h5><%= tv.name %></h5>
      <p><%= tv.description %>Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <div class="tv-index-extra-info border-top pt-1 pb-1">
      <div class="product-price">
        £<%= tv.price %>
      </div>
      <div class="product-size border-top pt-1 pb-1">
        <%= tv.size %>" inch
      </div>
      <div class="date-listed border-bottom border-top pt-1 pb-1">
        Date Listed <%= Date.today %>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
</div>

app/views/shared/_cardhome.html.erb
<div class="row text-center">
  <div class="col-12 order-prcess-title p-5">
    <h2 class="order-title border-bottom p-3">Order Process</h2>
  </div>
  <div class="col-12 col-md-6 col-lg-6">
    <p>CHOOSE YOUR TV</p>
  <div class="card-trip">
    <img src="https://images.unsplash.com/photo-1542744095-291d1f67b221?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80" alt="">
  </div>
  </div>
  <div class="col-12 col-md-6 col-lg-6">
    <p>PLACE YOUR ORDER</p>
  <div class="card-trip">
    <img src="https://images.unsplash.com/photo-1542744095-291d1f67b221?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80" alt="">
  </div>
  </div>
  <div class="col-12 col-md-6 col-lg-6">
    <p>SIT BACK & WAIT FOR A CALL FROM US</p>
  <div class="card-trip">
    <img src="https://images.unsplash.com/photo-1542744095-291d1f67b221?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80" alt="">
  </div>
  </div>
  <div class="col-12 col-md-6 col-lg-6">
    <p>WE'LL DELIVER & YOU PAY ON THE DAY</p>
  <div class="card-trip">
    <img src="https://images.unsplash.com/photo-1542744095-291d1f67b221?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80" alt="">
  </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="whole-footer border-property">
  <div class="footer row">
    <div class="aligned col-6 col-md-4 justify-content-center">
      <div class="ptags text-left">
        <%= link_to "Customer Service", tvs_path, class: "nav-link" %>
        <%= link_to "About Us", tvs_path, class: "nav-link" %>
        <%= link_to "Contact Us", tvs_path, class: "nav-link" %>
      </div>
    </div>
      <div class="aligned col-6 col-md-4 justify-content-center">
      <div class="ptags text-center">
        <%= link_to "TV Range", tvs_path, class: "nav-link" %>
        <%= link_to "Delivery/Terms", tvs_path, class: "nav-link" %>
        <%= link_to "1", tvs_path, class: "nav-link" %>
      </div>
    </div>
    <div class="aligned col-6 col-md-4 justify-content-center">
      <div class="ptags text-right">
        <%= link_to "FAQS", tvs_path, class: "nav-link" %>
        <%= link_to "Privacy Policy", tvs_path, class: "nav-link" %>
        <%= link_to "2", tvs_path, class: "nav-link" %>
      </div>
    </div>
  </div>

  <div class="social-links text-center d-flex justify-content-center border-property pb-4 pt-4">
    <div class="links mr-5">
      <a href="https://www.instagram.com/discounttv/?hl=en" target="_blank" rel="noopener noreferrer"><i class="fab fa-instagram fa-1x"></i></a>
      <a href="#"><i class="fab fa-facebook fa-1x"></i></a>
    </div>
    <div class="credit-image ml-5">
      <img id="creditcards" target="_blank" rel="noopener noreferrer" src="//assets.ransomspares.co.uk/Shop/Images/CreditCards.png" alt="">
    </div>
  </div>

  <div class="border-property text-center p-4">
    <p>DISCOUNT TVS 2020 © ALL RIGHTS RESERVED</p>
  </div>
</div>

app/views/shared/_form.html.erb
<div class=" form-container m-4 p-4">
  <h2 class="contact-title text-center "> Get in touch</h2>
  <h6 class="text-center contact-heading pb-4">Let's find you the perfect TV</h6>
  <div class="full-form">
    <form
      action="https://formspree.io/f/maylbbpb"
      method="POST">
    <div class=" d-flex form--inputs-top">
      <div class="name-label">
        <label>
        Name
          <input type="text" name="name" class="input">
        </label>
      </div>
      <div class="email-label">
        <label>
        Email
          <input type="text" name="_replyto" class="input">
        </label>
      </div>
      <div class="phone-label">
        <label>
        Phone Number
          <input type="text" name="_replyto" class="input">
        </label>
      </div>
    </div>
    <div class="form--input-bottom">
      <label class="message--input">
      Your Message
        <textarea name="message" class="input p-1"></textarea>
      </label>
    </div>
    <div class="text-center m-3">
      <button class="dtv-button" type="submit">Send</button>
    </div>
    </form>
  </div>
  <div class="contact-details mt-5 pt- text-center">
    <h6>Discount Digital LTD | 86-90 Paul Street, London, UK</h6>
    <h6>0203 411 3462</h6>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header>
  <div class="nav-conatiner">
    <input type="checkbox" name="" id="check">
    <div class="logo-container">
      <%= link_to root_path do %>
      <%= image_tag "https://discounttvs.co.uk/wp-content/uploads/2020/01/Logo-3.png", class: "nav-logo" %>
      <% end %>
    </div>

    <div class="nav-btn">


      <div class="navbar-links">
        <ul>
          <li class="nav-link" style="--i: .6s">
            <a href="#">Range<i class="fas fa-caret-down rotate"></i></a>
            <div class="dropdown">
              <ul>
                <li class="arrow"></li>
                </li>
                  <li class="dropdown-link">
                  <%= link_to "All TVs", tvs_path %>
                </li>
                <li class="dropdown-link">
                  <%= link_to "4K", tvs_path %>
                </li>
                <li class="dropdown-link">
                  <%= link_to "8K", tvs_path %>
                </li>
                <li class="dropdown-link">
                  <%= link_to "OLED", tvs_path %>
                </li>
                <li class="dropdown-link">
                  <%= link_to "Curved TV", tvs_path %>
                </li>
                 <li class="dropdown-link">
                  <%= link_to "Frame TV", tvs_path %>
              </ul>
            </div>
          </li>
         <!--  <li class="nav-link" style="--i: 1.4s">
            <%#= link_to 'Our Tvs', tvs_path %>
          </li> -->
          <li class="nav-link" style="--i: 1.8s">
            <%= link_to 'About Us', root_path %>
          </li>
          <% if current_user.try(:admin?) == true %>
            <li class="nav-link" style="--i: 2.2s">
              <%= link_to "Create Tv", new_tv_path %>
            </li>
          <% end %>
          <% if user_signed_in? %>
          <li class="nav-link" style="--i: 1.8s">
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
          </li>
          <% else %>
          <li class="nav-link" style="--i: 1.8s">
            <%= link_to 'Log In', new_user_session_path %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="hamburger-menu-container">
        <div class="hamburger-menu">
          <div></div>
        </div>
    </div>
  </div>
</header>

app/views/shared/_search.html.erb
<div class="row">
    <div class ='search_bar mb-5'>
      <div id="affect"><%= form_tag tvs_path method: :get do %></div>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control h70",
          placeholder: "Search product or brand"%>
          <div class="button--search">
            <%= button_tag type: 'submit', class: "button postfix" do %>
              <i class="fa fa-search" aria-hidden="true"></i>
            <% end %>
          </div>
      <% end %>
    </div>
</div>

app/views/shared/_similartv-card.html.erb
<% @similar_tvs.each do |tv| %>
<%= link_to tv_path(tv) do %>

<div class="tvindex-card-style">
  <div class="product-card" style="width: 12rem;">
    <div class="product-image border-bottom bg-grey pb-2">
      <img class="card-img"  src="https://discounttvs.co.uk/wp-content/uploads/2020/02/4K-TV.jpg" alt="Card image cap">
    </div>
    <!-- <div class="product-image" style="background-image: url(<%#= tv.photos.first ? (cl_image_path tv.photos.first.key, crop: :fill) : ""  %>)"></div> -->
    <div class="product-description pt-1">
      <h5><%= tv.name %></h5>
      <p><%= tv.description %>Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <div class="extra-info border-top pt-1 pb-1">
      <div class="product-price">
        £<%= tv.price %>
      </div>
      <div class="product-size border-top pt-1 pb-1">
        <%= tv.size %>" inch
      </div>
      <div class="date-listed border-bottom border-top pt-1 pb-1">
        Date Listed <%= Date.today %>
      </div>
    </div>
  </div>

</div>

<% end %>
<% end %>

app/views/shared/_tvsindex-card.html.erb
<div class="tvindex-card-style">
  <% @tvs.each do |tv| %>
  <%= link_to tv_path(tv) do %>
  <div class="product-card" style="width: 12rem;">
    <div class="product-image border-bottom bg-grey pb-2">
      <img class="card-img"  src="https://discounttvs.co.uk/wp-content/uploads/2020/02/4K-TV.jpg" alt="Card image cap">
    </div>
    <!-- <div class="product-image" style="background-image: url(<%#= tv.photos.first ? (cl_image_path tv.photos.first.key, crop: :fill) : ""  %>)"></div> -->
    <div class="product-description pt-1">
      <h5><%= tv.name %></h5>
      <p><%= tv.description %>Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <div class="extra-info border-top pt-1 pb-1">
      <div class="product-price">
        £<%= tv.price %>
      </div>
      <div class="product-size border-top pt-1 pb-1">
        <%= tv.size %>" inch
      </div>
      <div class="date-listed border-bottom border-top pt-1 pb-1">
        Date Listed <%= Date.today %>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
</div>

app/views/shared/_tvsindex.html.erb
<div class="tvindex-card-style">
  <% @tvs.each do |tv| %>
  <%= link_to tv_path(tv) do %>
  <div class="product-card" style="width: 18rem;">
    <div class="product-image border-bottom bg-grey pb-2">
      <img class="card-img"  src="https://discounttvs.co.uk/wp-content/uploads/2020/02/4K-TV.jpg" alt="Card image cap">
    </div>
    <!-- <div class="product-image" style="background-image: url(<%#= tv.photos.first ? (cl_image_path tv.photos.first.key, crop: :fill) : ""  %>)"></div> -->
    <div class="product-description pt-1">
      <h5><%= tv.name %></h5>
      <p><%= tv.description %>Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
    <div class="extra-info border-top pt-1 pb-1">
      <div class="product-price">
        £<%= tv.price %>
      </div>
      <div class="product-size border-top pt-1 pb-1">
        <%= tv.size %>" inch
      </div>
      <div class="date-listed border-bottom border-top pt-1 pb-1">
        Date Listed <%= Date.today %>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
</div>

app/views/tvs/_form.html.erb
<%= simple_form_for (@tv) do |f| %>

<div>
  <%= f.input :name %>
  <%= f.input :model %>
  <%= f.input :photo, as: :file %>
</div>



<%= end %>

app/views/tvs/index.html.erb
<div class="container">
  <div class="banner-container" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1555215695-3004980ad54e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2100&q=80);">
  </div>
  <div class="heading-container">
    <p id="index-page-heading">'TV'</p>
  </div>
    <ol class="breadcrumbs-list">
      <%= link_to root_path do %>
        <li class="breadcrumbs-item-home">Home</li>
      <% end %>
       <li class="breadcrumbs-item"> <%= link_to "All TVs", tvs_path %></li>
    </ol>
  <div class="index-page-row">
    <div class="filter-container col-lg-3">
      <%= simple_form_for :search, url: tvs_path,  method: :get, remote: true do |f|%>
        <%= f.input :brand, collection: @tvs_all.map(&:brand).uniq %>
        <%= f.input :price, collection: @tvs_all.map(&:price).uniq %>
        <%= f.input :size, collection: @tvs_all.map(&:size).uniq %>
        <%= f.input :year, collection: @tvs_all.map(&:year).uniq %>
        <div class="text-center mb-4">
          <%= f.submit "Search", class: "dtv-button" %>
        </div>
        <div class="text-center">
          <%= link_to 'View All', tvs_path, class: "dtv-button-light" %>
        </div>
      <% end %>
    </div>
    <div class="product-grid col-lg-9">
      <%= render 'shared/tvsindex-card', tvs: @tvs %>
    </div>
  </div>
</div>

<div class="trust-pilot-container text-center p-5">
  <p>Trust Pilot Rating</p>
</div>
<div class="recently-viewed-container text-center p-5">
  <p>Recently Viewed Items</p>
  <%#= render 'shared/tvsindex-card', tvs: @tvs %>
</div>





  <!-- <%# if current_user.try(:admin?) == true %>
      <div class="ml-5">
        <%#= link_to 'Create Tv', new_tv_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  <%# end %> -->

app/views/tvs/index.js.erb
document.querySelector('#tvs').innerHTML = "<%= j (render 'shared/tvsindex-card', tvs: @tvs) %>";

app/views/tvs/show.html.erb
<div class="container">
  <div class="tv-showpage-container">

    <div class="row">
      <div class="photo-gallery col-lg-8 col-md-8 col-sm-12 ">
        <% if @tv.photos.any? %>
        <%= cl_image_tag @tv.photos.first.key, class: "main-gallery-image", crop: :fill %>
        <div class="scroll-row">
          <% @tv.photos.each do |photo| %>
            <%= cl_image_tag photo.key, class: "scroll_image", crop: :fill %>
          <% end %>
        </div>
        <% end %>
      </div>

      <div class="tv-specs col-lg-4 col-md-4 col-sm-12">
        <h4>Tv name</h4>
        <p><%= @tv.name %></p>
        <h4>Tv size</h4>
        <div class="dropdown mb-3 ">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Choose your size
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#"><p><%= @tv.size %>"</p></a>
          </div>
        </div>
        <h4>Price</h4>
        <p>£<%= @tv.price %></p>

        <div class="checkboxes">
          <div class="form-check form-check">
            <input type="checkbox" class="form-check-input" id="checkbox" value="25" name="input1">
            <label class="form-check-label" for="materialInline1">TV Recycling(£25)</label>
          </div>

          <div class="form-check form-check">
            <input type="checkbox" class="form-check-input" id="materialInline2" value="40">
            <label class="form-check-label" for="materialInline2">Full TV Installation and set up (£40)</label>
          </div>
        </div>
      <%= link_to 'Continue Shopping', tvs_path, class: "btn btn-primary"%>
      </div>

    </div>

    <div class="product-description-container border">
      <h4>Description</h4>
      <p><%= @tv.description %></p>

    </div>


  <!-- <script>
  document.getElementById('checkbox').onchange = function()  {
    document.getElementById('input1').setAttribute(this.checked ? <%= @tv.price %> : <%= @tv.price %>)
  }
  </script>
   -->

    <div>
      <% if current_user.try(:admin?) == true %>
      <%= link_to "Edit", edit_tv_path(@tv), class: "btn btn-primary"%>
      <%= link_to "Delete", tv_path(@tv), class: "btn btn-primary", method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>

    <% if @similar_tvs %>
      <div class="border text-center">
        <h2>Customers also viewed</h2>
        <div class="row">
          <%= render 'shared/similartv-card' %>
        </div>
      </div>
    <% end %>

  </div>
</div>


<script>
  document.querySelectorAll(".scroll_image").forEach((e) => {
    e.addEventListener("click", (event) => {
      document.querySelector(".main-gallery-image").src = event.target.src
    })
  })
</script>